### ISSUE TITLE
menu tray bugs 

### ISSUE THREAD

**Issue by mmikeww** [mmikeww/AHK-v2-script-converter#179]
from forum
https://www.autohotkey.com/boards/viewtopic.php?p=573895&sid=a856ddeab374f28658a4e1d432887b4e#p573895

**Comment by Banaanae** [comment]
Icons were fixed in #126, but the fix isn't running, example one should be an easy fix

**Comment by andymbody** [comment]
I think the following will fix this line 
`Menu, Tray, Icon, %A_ScriptDir%\WallpaperLauncher\screen.ico   ;Add tray icon`

```
   menuNameLine := Trim(menuNameLine)   ; currently at about line 2292
   ; fix #179
   if (menuNameLine="Tray" && menuList="|Tray|" && Var2="Icon")
   {
      LineResult .= "TraySetIcon(" ToStringExpr(Var3)
      LineResult .= Var4 ? "," ToStringExpr(Var4) : ""
      LineResult .= Var5 ? "," ToStringExpr(Var5) : ""
      LineResult .= ")"
      Return LineResult
   }
```

**Comment by andymbody** [comment]
I think this should fix this issue (add this IF). There is also some code that can be removed, but not included here.

Please test on your end

```
   menuNameLine := Trim(menuNameLine)   ; currently at about line 2292
   ; fix #179
   if (menuNameLine="Tray" && menuList="|Tray|")
   {
      if (Var2 = "Tip")
      {
         Return LineResult .= "A_IconTip := " ToStringExpr(Var3)
      }
      else if (Var2 = "Icon")
      {
         LineResult .= "TraySetIcon(" ToStringExpr(Var3)
         LineResult .= Var4 ? "," ToStringExpr(Var4) : ""
         LineResult .= Var5 ? "," ToStringExpr(Var5) : ""
         LineResult .= ")"
         Return LineResult
      }
   }
```

**Comment by andymbody** [comment]
I think this should fix this issue (add this IF). There is also some code that can be removed, but not included here. I will test further and submit a PR unless you want to...

Please test on your end

```
   menuNameLine := Trim(menuNameLine)   ; currently at about line 2292
   ; fix #179
   if (menuNameLine="Tray" && menuList="|Tray|")
   {
      if (Var2 = "Tip")
      {
         Return LineResult .= "A_IconTip := " ToStringExpr(Var3)
      }
      else if (Var2 = "Icon")
      {
         LineResult .= "TraySetIcon(" ToStringExpr(Var3)
         LineResult .= Var4 ? "," ToStringExpr(Var4) : ""
         LineResult .= Var5 ? "," ToStringExpr(Var5) : ""
         LineResult .= ")"
         Return LineResult
      }
   }
```

**Comment by andymbody** [comment]
Proposed fix...

I think this edit should fix this issue. Do you want to test before PR is submitted? The edit might also be able to be simplified...

```
   menuNameLine := Trim(menuNameLine)   ; existing code at about line 2292
   ; fix #179
   if (menuNameLine="Tray")
   {
      if (Var2 = "Tip")
      {
         Return LineResult .= "A_IconTip := " ToStringExpr(Var3)
      }
      else if (Var2 = "Icon")
      {
         LineResult .= "TraySetIcon(" ToStringExpr(Var3)
         LineResult .= Var4 ? "," ToStringExpr(Var4) : ""
         LineResult .= Var5 ? "," ToStringExpr(Var5) : ""
         LineResult .= ")"
         Return LineResult
      }
   }

   if (!InStr(menuList, "|" menuNameLine "|"))
   {
      if (menuNameLine = "Tray")
      {
;         if (Var2 = "Tip") {
;            Return LineResult .= "A_IconTip := " ToStringExpr(Var3)
;         }
;         if (Var2 = "Icon"){
;;            Var2 := "SetIcon" ; not needed
;            LineResult .= "TraySetIcon(" ToStringExpr(Var3)
;            LineResult .= Var4 ? "," ToStringExpr(Var4) : ""
;            LineResult .= Var5 ? "," ToStringExpr(Var5) : ""
;            LineResult .= ")"
;            Return LineResult
;         }
         LineResult .= menuNameLine ":= A_TrayMenu`r`n" Indentation
      }
      else
      {
         LineResult .= menuNameLine " := Menu()`r`n" Indentation
      }
      menuList .= menuNameLine "|"
   }

   LineResult .= menuNameLine "."       ; existing code
```

**Comment by andymbody** [comment]
Proposed fix...

I think this edit should fix this issue. Do you want to test prior to a PR being submitted?

```
   menuNameLine := Trim(menuNameLine)   ; existing code at about line 2292
   ; fix #179
   if (menuNameLine="Tray")
   {
      if (Var2 = "Tip")
      {
         Return LineResult .= "A_IconTip := " ToStringExpr(Var3)
      }
      else if (Var2 = "Icon")
      {
         LineResult .= "TraySetIcon(" ToStringExpr(Var3)
         LineResult .= Var4 ? "," ToStringExpr(Var4) : ""
         LineResult .= Var5 ? "," ToStringExpr(Var5) : ""
         LineResult .= ")"
         Return LineResult
      }
   }

   if (!InStr(menuList, "|" menuNameLine "|"))
   {
      if (menuNameLine = "Tray")
      {
         ; MOVED TO ABOVE
;         if (Var2 = "Tip") {
;            Return LineResult .= "A_IconTip := " ToStringExpr(Var3)
;         }
;         if (Var2 = "Icon"){
;;            Var2 := "SetIcon" ; not needed
;            LineResult .= "TraySetIcon(" ToStringExpr(Var3)
;            LineResult .= Var4 ? "," ToStringExpr(Var4) : ""
;            LineResult .= Var5 ? "," ToStringExpr(Var5) : ""
;            LineResult .= ")"
;            Return LineResult
;         }
         LineResult .= menuNameLine ":= A_TrayMenu`r`n" Indentation
      }
      else
      {
         LineResult .= menuNameLine " := Menu()`r`n" Indentation
      }
      menuList .= menuNameLine "|"
   }

   LineResult .= menuNameLine "."       ; existing code
```

**Comment by mmikeww** [comment]
you can submit the PR and then we can test

typically the work flow is:

1. you test on your local machine and try to get it as clean as possible before sharing
2. you upload to branch on your personal repository
3. you submit PR into main repository pointing to your branch
4. people can review and test your PR code 
5. if suggestions/changes need to be made, you update your PR accordingly
6. people retest your changes
7. if looks good, PR is accepted and merged into main repository

**Comment by andymbody** [comment]
> you can submit the PR and then we can test
>
Ok... will do... thanks...

**Comment by Banaanae** [comment]
Fixed in #182

**Comment by andymbody** [comment]
The OP posted an update after testing this fix, and it was not fixed. I made an adjustment to fix it. Does this require a new issue to be created, or can this one be reopened? I am almost ready to post the updated fix, but wanted to find out how to handle this.

**Comment by mmikeww** [comment]
You can just create a new PR directly and mention this issue
